# Generated by Django 2.2.10 on 2020-03-25 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kl_participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('hostname', models.CharField(max_length=1024, unique=True)),
                ('api_secret', models.CharField(max_length=64)),
                ('region', models.CharField(choices=[('dolnoslaskie', 'dolnoslaskie'), ('slaskie', 'slaskie')], max_length=32, null=True)),
                ('cpu_count', models.SmallIntegerField(null=True)),
                ('load_5m', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('last_heartbeat', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'server_nodes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_participants.Group')),
                ('server_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_conferences.ServerNode')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
