# Generated by Django 2.2 on 2020-03-24 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kl_participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'server_nodes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_participants.Group')),
                ('server_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_conferences.ServerNode')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
