# Generated by Django 2.2.10 on 2020-03-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl_conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='attendee_secret',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='moderator_secret',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='servernode',
            name='region',
            field=models.CharField(choices=[('dolnoslaskie', 'dolnoslaskie'), ('kujawsko_pomorskie', 'kujawsko_pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('lodzkie', 'lodzkie'), ('malopolskie', 'malopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('slaskie', 'slaskie'), ('swietokrzyskie', 'swietokrzyskie'), ('warminsko_mazurskie', 'warminsko_mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=32, null=True),
        ),
    ]
