# Generated by Django 2.2.10 on 2020-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl_conferences', '0002_auto_20200327_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernode',
            name='last_assigned',
            field=models.DateTimeField(null=True),
        ),
    ]
