# Generated by Django 2.2.10 on 2020-04-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl_conferences', '0004_room_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernode',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
