# Generated by Django 2.2.10 on 2020-12-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kl_participants', '0006_student_last_accessed'),
        ('kl_conferences', '0005_servernode_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_participants.Group')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kl_conferences.ServerNode')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('server', 'group')},
            },
        ),
    ]
