# Generated by Django 2.2.10 on 2020-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl_participants', '0002_auto_20200327_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='access_token',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
