# Generated by Django 2.2.10 on 2020-04-06 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kl_participants', '0004_auto_20200402_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
