# Generated by Django 2.2.10 on 2020-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kl_conferences', '0006_preferredserver'),
        ('kl_participants', '0006_student_last_accessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='preferred_servers',
            field=models.ManyToManyField(through='kl_conferences.PreferredServer', to='kl_conferences.ServerNode'),
        ),
    ]
